# Generated by Django 2.1.3 on 2018-11-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='numero',
            field=models.CharField(max_length=20),
        ),
    ]
